.. list-table::
   :widths: 30 40 30
   :header-rows: 0

   * - .. figure:: img/liedetect
        :figclass: align-center

     - LieDetect is an algorithm to estimate representation types of compact Lie groups from finite samples of their orbits. Currently implemented for :math:`SO(2)`, :math:`T^d`, :math:`SO(3)`, and :math:`SU(2)`.

     - :Authors: Henrique Ennes & Raphaël Tinarrage
       :Since: GUDHI 3.11.0
       :License: MIT (`GPL v3 </licensing/>`_)
       :Requires: 

   * - * :doc:`liedetect_user`
     - * :doc:`liedetec_orbit_fitter_ref`
     - * :doc:`liedetec_orhtonomalize_ref`
